<a href="https://colab.research.google.com/github/ashwini-mohidekar/neural-networks-basics/blob/main/Playing_with_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu128
True


In [ ]:
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


##Multiplying two multi dimensional tensors

In [ ]:
tens_a = torch.tensor([[10,11,12,13], [14,15,16,17]])
tens_b = torch.tensor([[18,19,20,21], [22,23,24,25]])
multi_tens = tens_a * tens_b
print(multi_tens)

tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]])


##Different ways to create Tensors

In [ ]:
# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])

# initialize a tensor from a tuple
tensor_from_tuple=torch.tensor((6,7,8,9,10))

print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

# initialize a tensor from a ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_array)

tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp) #empty function

tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros) #zero function

tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones) #ones function

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])
Tensor from array: tensor([11, 12, 13, 14, 15])
tensor_emp : tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20, 6.1943e-04],
        [3.6022e-12, 6.9989e+22, 2.6330e+20, 6.1943e-04],
        [3.6022e-12, 7.1223e+28, 3.0958e-18, 2.6532e+20]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)

# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)

# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)


tensor_rand_un : tensor([[0.9715, 0.8195, 0.8490, 0.7386, 0.9037],
        [0.4742, 0.7769, 0.5507, 0.7226, 0.9385],
        [0.3279, 0.0822, 0.3258, 0.9600, 0.5848],
        [0.5803, 0.4361, 0.0808, 0.5621, 0.0061]])
tensor_rand_norm : tensor([[-0.0877, -1.4330, -0.0771, -0.8795, -1.0413],
        [-0.2623,  0.3941,  1.1010,  0.1222,  1.4092],
        [ 0.5405, -0.7563,  0.1253, -0.7981, -0.6108],
        [-0.0928, -0.1389, -1.5007,  0.6421, -1.5101]])
tensor_rand_int : tensor([[9, 6, 8, 7, 8],
        [8, 7, 5, 7, 7],
        [6, 9, 8, 9, 8],
        [6, 6, 5, 8, 9]])


##Tensor Attributes

Knowing device location, datatype, dimension and rank is very important

In [ ]:
first_tensor = torch.tensor([1,2,3,4,5,6])

torch.device indicates the tensor’s device location

In [ ]:
first_tensor.device

device(type='cpu')

torch.dtype indicates the tensor's datatype

In [ ]:
first_tensor.dtype

torch.int64

torch.shape() shows the tensor's dimensions

In [ ]:
first_tensor.shape

torch.Size([6])

torch.ndim identifies the number of a tensor's dimensions

In [ ]:
first_tensor.ndim

1

In [ ]:
second_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
second_tensor.dtype

torch.int64

In [ ]:
second_tensor.shape

torch.Size([3, 3])

In [ ]:
second_tensor.ndim

2

##Tensor data types

In [3]:
#Integer data type tensor
int_tensor= torch.tensor([1,2,3,4,5],dtype=torch.int8)
int_tensor.dtype

torch.int8

In [4]:
#Float Tensor
float_tensor = torch.tensor([6,7,8,9,10], dtype=torch.float32)
float_tensor.dtype

torch.float32

In [5]:
#Short Tensor
short_tensor = torch.tensor([11,12,13,14,15], dtype=torch.int16)
short_tensor.dtype

torch.int16

In [6]:
#Casting a tensor to a new datatype - method 1
int_tensor = int_tensor.float()
int_tensor.dtype

torch.float32

In [7]:
#Casting a tensor to a new datatype - method 2
short_tensor = short_tensor.to(dtype=torch.int8)
short_tensor.dtype

torch.int8

##Creating Tensors from Random samples

In [10]:
torch.manual_seed(111)
torch.rand(3,3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])

In [11]:
torch.randint(-1,10,(3,3))

tensor([[9, 2, 6],
        [5, 6, 0],
        [5, 3, 9]])

##Simple Tensors

In [12]:
#Create a tensor of shape(2,5) filled with ones
tensor1 = torch.zeros(2,5)
tensor1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [13]:
#Create a tensor with shape(2,5) filled with random numbers
tensor2 = torch.rand(2,5)
tensor2

tensor([[0.4400, 0.6341, 0.6224, 0.6334, 0.8580],
        [0.1572, 0.7853, 0.1458, 0.4177, 0.3047]])

In [15]:
#Create a tensor with the shape(2,5) filled with ones
tensor3 = torch.ones_like(tensor1)
tensor3

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
#Create a tensor with shape(2,5) with provided values
tensor4 = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
tensor4
torch.full_like(tensor1, 7)
torch.full((4,5),5)

tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])

In [22]:
#Practice Time!

input_list = [[1,2,3,4,5],[6,7,8,9,10]]
input_array = np.array([[11,12,13],[14,15,16]])

def create_tensor_from_list(input_list):
    return torch.tensor(input_list)

def create_tensor_from_array(input_array):
    return torch.tensor(input_array)

def create_tensor_ones():
    return torch.ones(3,4)

def create_tensor_full():
    return torch.full((4,5),5)

##Tensor Operations

In [25]:
#Indexing and slicing a 1-dim tensor
one_dim_tensor = torch.tensor([1,2,3,4,5,6,7,8])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

#Slicing
one_dim_tensor[1:4]

tensor(3)
3


tensor([2, 3, 4])

In [30]:
#Indexing and slicing a 2-dim tensor
two_dim_tensor = torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
print(two_dim_tensor[1][3])
print(two_dim_tensor[1,3].item())

print("first three elements of the 1st row:", two_dim_tensor[0,0:3])
print("first three elements of the 2nd row:", two_dim_tensor[1,0:3])

tensor(10)
10
first three elements of the 1st row: tensor([1, 2, 3])
first three elements of the 2nd row: tensor([7, 8, 9])


In [31]:
#Indexing data that meets some critera
two_dim_tensor[two_dim_tensor < 11]

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
#Combining Tensors
torch.stack((two_dim_tensor, two_dim_tensor))

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

In [34]:
#Splitting Tensors
first_tensor, second_tensor, third_tensor, fourth_tensor=torch.unbind((two_dim_tensor))
print(first_tensor, second_tensor, third_tensor, fourth_tensor)

tensor([1, 2, 3, 4, 5, 6]) tensor([ 7,  8,  9, 10, 11, 12]) tensor([13, 14, 15, 16, 17, 18]) tensor([19, 20, 21, 22, 23, 24])


In [35]:
#Splitting 2-dim tensor
torch.unbind(two_dim_tensor, dim=1)

(tensor([ 1,  7, 13, 19]),
 tensor([ 2,  8, 14, 20]),
 tensor([ 3,  9, 15, 21]),
 tensor([ 4, 10, 16, 22]),
 tensor([ 5, 11, 17, 23]),
 tensor([ 6, 12, 18, 24]))

##Mathematical Functions

###Basic Math Functions

In [37]:
#Basic Math functions
a = torch.tensor([10,2,8,6,4])
b = torch.tensor([1,2,4,3,1])

print("Adding Tensors a and b: ",a.add(b))
print("Multiplying Tensors a and b: ", a.mul(b))
print("Dividing Tensors a and b: " , a.div(b))

Adding Tensors a and b:  tensor([11,  4, 12,  9,  5])
Multiplying Tensors a and b:  tensor([10,  4, 32, 18,  4])
Dividing Tensors a and b:  tensor([10.,  1.,  2.,  2.,  4.])


###Reduction Functions

In [39]:
#Reduction Functions
c = torch.tensor([[20., 14., 11., 8.], [3., 19., 14., 6.]])

print("Mean of the tensor c: " , torch.mean(c))
print("Median of the tensor c: ", torch.median(c))
print("Mode of the tensor c: " , torch.mode(c))
print("Standard deviation of the tensor c: " , torch.std(c))

Mean of the tensor c:  tensor(11.8750)
Median of the tensor c:  tensor(11.)
Mode of the tensor c:  torch.return_types.mode(
values=tensor([8., 3.]),
indices=tensor([3, 0]))
Standard deviation of the tensor c:  tensor(6.0341)


##Linear Algebra Operations

In [41]:
#Compute the dot product(scalar) of two 1-d tensors

first_tensor = torch.tensor([1,2,3])
second_tensor = torch.tensor([4,5,6])
dot_product = torch.matmul(first_tensor, second_tensor)
dot_product

tensor(32)

In [42]:
#Compute the matrix-matrix product(2D Tensor) of 2D Tensors

first_2d_tensor = torch.tensor([[1,2,3],[-1,-2,-3]])
second_2d_tensor = torch.tensor([[-1,-2], [4,5], [4,5]])

result_2d_tensor = torch.matmul(first_2d_tensor, second_2d_tensor)
result_2d_tensor

tensor([[ 19,  23],
        [-19, -23]])

In [43]:
#Compute the matrix product of 5 2D Tensors

first_tensor = torch.randn(2,3)
second_tensor = torch.randn(3,4)
third_tensor = torch.randn(4,5)
fourth_tensor = torch.randn(5,6)
fifth_tensor = torch.randn(6,7)

torch.linalg.multi_dot((first_tensor,second_tensor,third_tensor,fourth_tensor,fifth_tensor))

tensor([[ -2.8628,   0.3759,  -0.4985,  -5.7852, -12.5720,  -2.8079,  -2.2545],
        [  0.9396,   1.6469,   3.6826,   1.7244,  11.3983,  -3.8002,  -7.0339]])

In [47]:
#Computing eigenvalues and eigenvectors

#Create a 3X3 square matrix
A = torch.randn(3,3)
print("Matrix A: ", A)

eigenvalues, eigenvectors = torch.linalg.eigh(A)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

Matrix A:  tensor([[-1.3098,  1.3768,  0.1874],
        [ 0.5951,  1.1549,  0.1737],
        [-1.7956,  1.3517,  1.3240]])
Eigenvalues:  tensor([-2.5860,  0.9092,  2.8459])
Eigenvectors:  tensor([[ 0.8211,  0.5048, -0.2664],
        [-0.3050,  0.7825,  0.5429],
        [ 0.4825, -0.3645,  0.7964]])


##Automatic Differentiation (Autograd)

In [49]:
#Define Tensors
x = torch.autograd.Variable(torch.tensor([2.0]), requires_grad=True)
y = torch.autograd.Variable(torch.tensor([1.0]), requires_grad=True)
z = torch.autograd.Variable(torch.tensor([5.0]), requires_grad=True)

#Compute gradients
a = x -y

f = z * a
print("Final value of function f: ", f)

f.backward()
print("Gradient value for x: ", x.grad)
print("Gradient value for y: ", y.grad)
print("Gradient value for z: ", z.grad)

Final value of function f:  tensor([5.], grad_fn=<MulBackward0>)
Gradient value for x:  tensor([5.])
Gradient value for y:  tensor([-5.])
Gradient value for z:  tensor([1.])
